---

- debug: msg={{ proj_dir }}
- debug: msg={{ proj_dir }}/{{ db_file_name }}

- name: mkdir
  file:
    path: "{{ proj_dir }}"
    state: directory

- name: Download file from bucket
  get_url:
    url: "{{ s3_bucket }}"
    dest:  "{{ proj_dir }}/{{db_file_name}}"
  register: everydb2

- name: Create db
  become: yes
  become_user: postgres
  postgresql_db:
    name: everydb2
    state: present
  when: everydb2.changed

- name: Restore database
  become: yes
  become_user: postgres
  postgresql_db:
    name: everydb2
    state: restore
    target: "{{ proj_dir }}/{{db_file_name}}"
  when: everydb2.changed

- name: Ensure we have access from the new user
  become: yes
  become_user: postgres
  postgresql_privs:
    db: everydb2
    role: uma
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE
  notify: Restart postgresql
  when: everydb2.changed

- shell: echo "$DB_UMA_PROCESSED $UMA_STATISTICS_FROM_DATE ~ $UMA_STATISTICS_TO_DATE"
  environment:
    PGHOST: "{{ec2_tag_Peer}}"
    PGPORT: "5432"
    PGUSER: "uma"
    PGPASSWORD: "password"
    DB_UMA_PROCESSED: "postgresql://uma:password@{{ec2_tag_Peer}}:5432/uma_processed"
    UMA_STATISTICS_FROM_DATE: "{{ ec2_tag_FromDate }}"
    UMA_STATISTICS_TO_DATE: "{{ ec2_tag_ToDate }}"
  register: return_from_shell

- name: show shell out
  debug:
    msg: "{{ return_from_shell.stdout }}"

- name: install python tools
  become: yes
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - python3-psycopg2
      - python3-tqdm
      - python-setuptools
    state: latest
    update_cache: True

- name: Copy script
  copy:
    src: "{{ script_name }}"
    dest: "{{ proj_dir }}/{{ script_name }}"
    owner: ubuntu
    group: ubuntu
    mode: 0777
  register: collectorpy

- name: execute script
  become: yes
  shell: "nohup python3 /tmp/uma_statistics_01/collector.py </dev/null 2>&1 >collector.log &"
  environment:
    PGHOST: "{{ec2_tag_Peer}}"
    PGPORT: "5432"
    PGUSER: "uma"
    PGPASSWORD: "password"
    DB_EVERYDB2: "postgresql://uma:password@localhost:5432/everydb2"
    DB_UMA_PROCESSED: "postgresql://uma:password@{{ec2_tag_Peer}}:5432/uma_processed"
    UMA_STATISTICS_FROM_DATE: "{{ ec2_tag_FromDate }}"
    UMA_STATISTICS_TO_DATE: "{{ ec2_tag_ToDate }}"
  when: collectorpy.changed

