- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create resources
      terraform:
        project_path: 'terraform/'
        state: present
      register: terraform

    - name: Upload Object
      shell: "aws s3 cp /tmp/uma_statistics_01/stat_src.sql s3://iwase22334-uma-everydb2store/uma_statistics_01/stat_src.sql --acl public-read"
      register: result
      changed_when: False

