############################################################
#               All                                        #
############################################################
- hosts: all
  remote_user: ubuntu
  become: True

  handlers:
    - name: Restart postgresql
      service: name=postgresql state=restarted enabled=yes

  roles:
    - postgres

############################################################
#               target db                                  #
############################################################
- hosts: tag_Role_processeddb
  remote_user: ubuntu
  become: True

  handlers:
    - name: Restart postgresql
      service: name=postgresql state=restarted enabled=yes

  vars:
    sqlfile_dst_dir: /tmp/uma_statistics_01
    sqlfile_name: create_uma_statistics_01.sql
    postgres_conf_dir: /etc/postgresql/11/main
    pgconf_name: postgresql.conf
    pghbaconf_name: pg_hba.conf

  roles:
    - processeddb

############################################################
#               data proceessor                            #
############################################################
- hosts: tag_Role_dataprocessor
  remote_user: ubuntu
  become: True

  handlers:
    - name: Restart postgresql
      service: name=postgresql state=restarted enabled=yes

  vars:
    proj_dir: /tmp/uma_statistics_01
    script_name: collector.py
    db_file_name: stat_src.sql
    s3_bucket: https://iwase22334-uma-everydb2store.s3-us-west-2.amazonaws.com/uma_statistics_01/stat_src.sql

  roles:
    - dataprocessor
